AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM Swagger.

Parameters:
  Env:
    Type: String
    Default: dev
  ArtifactBucket:
    Type: String
    Default: kaonashi-aws-sam-deploy-dev
Resources:
  KaonashiApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: !Sub s3://${ArtifactBucket}/swagger.yaml
  EmployeesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.6
      Handler: domain/employees/employees.get
      CodeUri: 
        Bucket: !Sub ${ArtifactBucket}
        Key: kaonashi-function.zip
      Role: !GetAtt LambdaRole.Arn
      VpcConfig:
        SecurityGroupIds:
        - { "Fn::ImportValue": !Join [ "-", [ "kaonashi", "application", "sg", "Ref":"Env"  ] ] }
        SubnetIds:
        - { "Fn::ImportValue": !Join [ "-", [ "kaonashi", "application", "subnet", "a", "Ref":"Env"  ] ] }
      Events:
        ApiProxy:
          Type: Api
          Properties:
            RestApiId: !Ref KaonashiApi
            Path: /employees
            Method: GET
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: "sts:AssumeRole"
      Policies:
        -
          PolicyName: "lambda_logs_policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "logs:*"
                Resource: "*"
              - Effect: "Allow"
                Action:
                  - ec2:CreateNetworkInterface
                  - ec2:DescribeNetworkInterfaces
                  - ec2:DetachNetworkInterface
                  - ec2:DeleteNetworkInterface
                Resource: "*"
                