AWSTemplateFormatVersion: 2010-09-09
Parameters:
  Env:
    Type: String
    Default: dev
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Join [ "-", [ "kaonashi-aws-sam-deploy", Ref: "Env" ] ]
      LifecycleConfiguration:
        Rules:
          - Status: Enabled
            ExpirationInDays: 14
    DeletionPolicy: Delete