AWSTemplateFormatVersion: 2010-09-09
Description: RDS(MySQL) create
Parameters:
  Env:
    Type: String
    Default: dev
  
Resources:
  DBSubnetGroup:
    Type: "AWS::RDS::DBSubnetGroup"
    Properties:
      DBSubnetGroupDescription: "RDS DB subnet group"
      SubnetIds:
      - { "Fn::ImportValue": !Join [ "-", [ "kaonashi", "private", "subnet" ,"a" , Ref: "Env" ] ] }
      - { "Fn::ImportValue": !Join [ "-", [ "kaonashi", "private", "subnet" ,"b" , Ref: "Env" ] ] }
      
  # Parameter Groupはデフォルト使用を想定
  RDS:
    Type: "AWS::RDS::DBInstance"
    Properties:
      AllocatedStorage: 20
      AllowMajorVersionUpgrade: false
      AutoMinorVersionUpgrade: true
      # Multi-Az使用時は指定できない
      AvailabilityZone: us-west-2a
      BackupRetentionPeriod: 0
      DBInstanceClass: db.t2.micro
      DBInstanceIdentifier: !Join [ "-", [ "kaonashi", "master", "db", Ref: "Env" ] ]
      DBSubnetGroupName: !Ref DBSubnetGroup
      Engine: mysql
      EngineVersion: 5.7
      MasterUsername: kaonashi
      MasterUserPassword: kaonashi4649
      MonitoringInterval: 0
      MultiAZ: false
      PubliclyAccessible: false
      StorageType: gp2
      VPCSecurityGroups:
      - { "Fn::ImportValue": !Join [ "-", [ "kaonashi", "rds", "sg" , Ref: "Env" ] ] }
