AWSTemplateFormatVersion: 2010-09-09
Parameters:
  Env:
    Type: String
    Default: dev

Resources:
  StepServer:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: !Join [ "-", [ Ref: "Env", "ssh", "key" ] ]
      ImageId: ami-0ad99772
      NetworkInterfaces:
      - AssociatePublicIpAddress: true
        DeviceIndex: 0
        GroupSet: 
        - { "Fn::ImportValue": !Join [ "-", [ "kaonashi", "step", "server", "sg", "Ref":"Env"  ] ] }
        SubnetId: { "Fn::ImportValue": !Join [ "-", [ "kaonashi", "public", "subnet", "a", "Ref":"Env"  ] ] }
      UserData: !Base64 |
        #!/bin/bash
        yum update -y
        yum install python36 -y
        yum install mysql mysql-devel -y
        yum install gcc -y
        yum install git -y
        ln -s /usr/bin/pip-3.6 /usr/bin/pip3
      Tags:
      - Key: Name
        Value: !Join [ "-", [ "kaonashi", "step", "server", "Ref":"Env"  ] ]
